{{- if .Values.keto.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keto
  namespace: dega
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keto
  template:
    metadata:
      labels:
        app: keto
    spec:
      containers:
      - image: oryd/keto:latest
        imagePullPolicy: Always
        name: keto
        env:
        - name: DSN
          value: postgres://postgres:***REMOVED***@kavach-postgresql.dega.svc.cluster.local:5432/keto
        ports:
        - name: http
          containerPort: 4466
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 100Mi
            cpu: 100m
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health/alive
            port: http
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
{{- end }}