apiVersion: v1
kind: Service
metadata:
  name: {{ include "hunting.fullname" . }}
  labels:
    {{- include "hunting.labels" . | nindent 4 }}
    {{- if .Values.service.additionalLabels }}
    {{- toYaml .Values.service.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "hunting.selectorLabels" . | nindent 4 }}
