{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hunting.fullname" . }}-flower
  labels:
    {{- include "hunting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http 
  selector:
    app.kubernetes.io/instance: hunting
    app.kubernetes.io/name: hunting-server-flower    
{{- end }}
