apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "server.fullname" . }}
  namespace: {{ template "dega.namespace" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.labels" . | nindent 8 }}
        {{- if .Values.server.podLabels }}
        {{- toYaml .Values.server.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.server.serviceAccount.create }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      {{- if or .Values.server.autoMigrate .Values.server.createSuperOrg }}        
      initContainers:
        {{- if .Values.server.autoMigrate}}
        - name: {{ .Values.server.name }}-automigrate
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args: ["migrate"]
          {{- if .Values.server.env }}
          env:
          {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}      
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: dega-server-data
              mountPath: ./app/data   
        {{- end }}
        {{- if .Values.server.createSuperOrg}}
        - name: {{ .Values.server.name }}-create-super-org
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args: ["create-super-org"]
          {{- if .Values.server.env }}
          env:
          {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}      
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: dega-server-data
              mountPath: ./app/data
        {{- end }}        
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- if .Values.server.env }}
          env:
          {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.server.service.portName }}
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
            {{ if .Values.server.metrics.enabled }}
            - name: {{ .Values.server.metrics.service.portName }}
              containerPort: {{ .Values.server.metrics.service.port }}
              protocol: TCP   
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.server.service.port }}
          #   initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}             
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.server.service.port }}
          #   initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}             
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: dega-server-data
              mountPath: ./app/data
            - name: dega-server-web
              mountPath: ./web/templates
            - name: dega-server-zt
              mountPath: ./app/zitadel_key.json
              # subPath: zitadel_key.json
      volumes:
        - name: dega-server-data
          configMap:
            name: dega-server-data
        - name: dega-server-web
          configMap:
            name: dega-server-web
        - name: dega-server-zt
          secret:
            secretName: zitadel-secret
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
