apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.fullname" . }}
  namespace: {{ template "dega.namespace" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
    {{- if .Values.server.service.labels }}
    {{- toYaml .Values.server.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.server.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8000
      protocol: TCP
      {{- if .Values.server.service.portName }}
      name: {{ .Values.server.service.portName }}
      {{- end }}
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: feeds