apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "server.fullname" . }}
  namespace: {{ template "vidcheck.namespace" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.labels" . | nindent 8 }}
        {{- if .Values.server.podLabels }}
        {{- toYaml .Values.server.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      {{- if or .Values.server.autoMigrate .Values.server.createSuperOrg }}        
      initContainers:
        {{- if .Values.server.autoMigrate}}
        - name: {{ .Values.server.name }}-automigrate
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args: ["migrate"]
          {{- if .Values.server.env }}
          env:
          {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}      
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: vidcheck-server-data
              mountPath: ./data             
        {{- end }}   
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- if .Values.server.env }}
          env:
          {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.server.service.portName }}
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
            {{ if .Values.server.metrics.enabled }}
            - name: {{ .Values.server.metrics.service.portName }}
              containerPort: {{ .Values.server.metrics.service.port }}
              protocol: TCP   
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health/alive
              port: {{ .Values.server.service.port }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}             
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.server.service.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}             
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: vidcheck-server-data
              mountPath: ./data
            - name: vidcheck-server-web
              mountPath: ./web/templates          
      volumes:
        - name: vidcheck-server-data
          configMap:
            name: vidcheck-server-data
        - name: vidcheck-server-web
          configMap:
            name: vidcheck-server-web               
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
