apiVersion: v1
kind: ConfigMap
metadata:
  name: vidcheck-server-data
  namespace: {{ template "vidcheck.namespace" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  {{- if .Values.server.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  {{- (.Files.Glob "data/server/**.json").AsConfig | nindent 2 }}