{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "meilisearch.fullname" . }}
  namespace: {{ template "meilisearch.namespace" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
    {{- if .Values.persistence.labels }}
    {{- toYaml .Values.persistence.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.persistence.annotations }}
  annotations:
  {{- range $key, $value := .Values.persistence.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}    
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}