{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "meilisearch.fullname" . }}
  namespace: {{ template "meilisearch.namespace" . }}
  labels:
    {{- include "meilisearch.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.selector }}
    {{- toYaml .Values.metrics.serviceMonitor.selector | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.labels }}
    {{- toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    port: metrics
    scheme: {{ .Values.metrics.serviceMonitor.scheme }}
  namespaceSelector:
    matchNames:
    - {{ template "meilisearch.namespace" . }}
  selector:
    matchLabels:
      {{- include "meilisearch.selectorLabels" . | nindent 6 }}
{{- end }}