# Default values for Imgproxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: imgproxy
fullnameOverride: imgproxy

## Override the deployment namespace
namespaceOverride: "apps"

imagePullSecrets: []

name: imgproxy

image:
  repository: darthsim/imgproxy
  pullPolicy: IfNotPresent
  tag: "v2.15.0"

# imagePullSecrets: []

# This value will be ignored if Autoscaling is enabled
replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## Environment variables to pass to Imgproxy
# All the possible congifurations possible are available here: https://github.com/imgproxy/imgproxy/blob/master/docs/configuration.md
env: {}


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # Labels to add to the service account
  labels: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "imgproxy"

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  portName: http
  annotations: {}
  labels: {}

metrics:
  enabled: false

  service:
    type: ClusterIP
    port: 8081
    portName: metrics
    annotations: {}
    labels: {}

  serviceMonitor:
    enabled: true
    selector:
      # prometheus: kube-prometheus
      release: monitoring
    labels: {}
    interval: 30s

    scheme: http
    tlsConfig: {}
    scrapeTimeout: 30s
    relabelings: []

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true' 
  ## Hostnames must be provided if Ingress is enabled.
  ## Secrets must be manually created in the namespace
  ##
  hosts:
    - change-to-your-domain.com
    - www.change-to-your-domain.com
  paths:
    - /
  extraPaths: []
  tls:
    - secretName: change-to-your-tls
      hosts:
        - change-to-your-domain.com
        - www.change-to-your-domain.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Readiness and liveness probes for default backend
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  periodSeconds: 10
livenessProbe:
  initialDelaySeconds: 50
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
  periodSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}
