apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.fullname" . }}
  namespace: {{ template "mande.namespace" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
    {{- if .Values.server.service.labels }}
    {{- toYaml .Values.server.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.server.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.public.port }}
      targetPort: 8002
      protocol: TCP
      {{- if .Values.server.service.public.portName }}
      name: {{ .Values.server.service.public.portName }}
      {{- end }}
    - port: {{ .Values.server.service.admin.port }}
      targetPort: 8000
      protocol: TCP
      {{- if .Values.server.service.admin.portName }}
      name: {{ .Values.server.service.admin.portName }}
      {{- end }}      
    - port: {{ .Values.server.service.ip.port }}
      targetPort: 8004
      protocol: TCP
      {{- if .Values.server.service.ip.portName }}
      name: {{ .Values.server.service.ip.portName }}
      {{- end }}
    - port: {{ .Values.server.service.api.port }}
      targetPort: 8006
      protocol: TCP
      {{- if .Values.server.service.api.portName }}
      name: {{ .Values.server.service.api.portName }}
      {{- end }}
    - port: {{ .Values.server.service.wf.port }}
      targetPort: 8005
      protocol: TCP
      {{- if .Values.server.service.wf.portName }}
      name: {{ .Values.server.service.wf.portName }}
      {{- end }}