apiVersion: v1
kind: ConfigMap
metadata:
  name: dega-studio-config
  namespace: {{ template "dega.namespace" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  {{- if .Values.studio.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.studio.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  config.js: |-
    {{- range $key, $value := .Values.studio.env }}
    window.{{ $value.name }} = {{ $value.value | quote}}
    {{- end }}