apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}
  namespace: {{ template "dega.namespace" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.studio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio.labels" . | nindent 8 }}
        {{- if .Values.studio.podLabels }}
        {{- toYaml .Values.studio.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.serviceAccount.create -}}
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.global.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.studio.name }}
          securityContext:
            {{- toYaml .Values.studio.securityContext | nindent 12 }}
          image: "{{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          {{- if .Values.studio.env }}
          env:
          {{- toYaml .Values.studio.env | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.studio.service.portName }}
              containerPort: {{ .Values.studio.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.studio.resources | nindent 12 }}
          volumeMounts:
            - name: dega-studio-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: dega-studio-config
          configMap:
            name: dega-studio-config
      {{- with .Values.studio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
