{{- if .Values.studio.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio.serviceAccountName" . }}
  namespace: {{ template "dega.namespace" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
    {{- if .Values.studio.serviceAccount.labels }}
    {{- toYaml .Values.studio.serviceAccount.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.studio.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.studio.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}