{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rill.fullname" . }}
  namespace: {{ include "rill.namespace" . }}
  labels:
    {{ include "rill.labels" . | nindent 4 }}
  annotations:
    {{ include "rill.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "rill.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "rill.PodLabels" . | nindent 8 }}
      annotations:
        {{ include "rill.PodAnnotations" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rill.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.portNumber }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if .Values.env }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: "/home/rill/dataful"
              {{- with .Values.persistence.subPath }}
              subPath: {{ tpl . $root }}
              readOnly: false
              {{- end }}
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
              readOnly: {{ .readOnly }}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  
      volumes:
        {{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ tpl (.Values.persistence.existingClaim | default (include "rill.fullname" .)) . }}
        {{- else }}
        - name: storage
          {{- if .Values.persistence.inMemory.enabled }}
          emptyDir:
            medium: Memory
            {{- with .Values.persistence.inMemory.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- range .Values.extraVolumes }}
        - name: {{ .name }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else if .hostPath }}
          hostPath:
            {{ toYaml .hostPath | nindent 6 }}
          {{- else if .csi }}
          csi:
            {{- toYaml .csi | nindent 6 }}
          {{- else if .configMap }}
          configMap:
            {{- toYaml .configMap | nindent 6 }}
          {{- else if .secret }}
          secret:
            {{- toYaml .secret | nindent 6 }}
          {{- else if .emptyDir }}
          emptyDir:
            {{- toYaml .emptyDir | nindent 6 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}