{{- if .Values.ingress.enabled -}}
{{- $fullName := include "companion.fullname" . -}}
{{- $serviceName := include "companion.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $paths := .Values.ingress.paths -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ template "companion.namespace" . }}  
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "companion.labels" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- if $extraPaths }}
  {{- toYaml $extraPaths | nindent 10 }}
  {{- end }}
  {{- range $p := $paths }}
          - pathType: ImplementationSpecific
            path: {{ $p }}
            backend:
              service:
                name: {{ $serviceName }}
                port: 
                  number: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
