apiVersion: v1
kind: Service
metadata:
  name: {{ template "imgproxy.fullname" . }}
  namespace: {{ template "imgproxy.namespace" . }}
  labels:
    {{- include "imgproxy.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "imgproxy.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      {{- if .Values.service.portName }}
      name: {{ .Values.service.portName }}
      {{- end }}