apiVersion: v1
kind: ConfigMap
metadata:
  name: kavach-web-config
  namespace: {{ template "kavach.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- if .Values.web.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.web.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  config.js: |-
    window.REACT_APP_KRATOS_PUBLIC_URL = 'https://kratos.factly.in';
    window.REACT_APP_API_URL = 'https://kavach-server.factly.in';
    window.REACT_APP_COMPANION_URL = "https://companion.factly.in";
    window.REACT_APP_KAVACH_TITLE = "Factly";