apiVersion: v1
kind: ConfigMap
metadata:
  name: kavach-web-config
  namespace: {{ template "kavach.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  {{- if .Values.web.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.web.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  config.js: |-
    {{- range $key, $value := .Values.web.env }}
    window.{{ $value.name }} = {{ $value.value | quote}}
    {{- end }}    