{{- if .Values.web.autoscaling.enabled }}
# apiVersion: autoscaling/v2
apiVersion: extensions/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "web.fullname" . }}
  namespace: {{ template "kavach.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kavach.fullname" . }}
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        # target:
        #   type: "Utilization"
        #   averageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
        targetAverageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        # target:
        #   type: "Utilization"
        #   averageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
        targetAverageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

