{{- if .Values.createSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "umami.fullname" . }}
  namespace: {{ template "umami.namespace" . }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.createSecret.postgresqlPostgresPassword }}
  postgresql-postgres-password: {{ .Values.createSecret.postgresqlPostgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.createSecret.postgresqlPassword }}
  postgresql-password: {{ .Values.createSecret.postgresqlPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.createSecret.postgresqlReplicationPassword }}
  postgresql-replication-password: {{ .Values.createSecret.postgresqlReplicationPassword | b64enc | quote }}
  {{- end }}
{{- end -}}