{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "imgproxy.fullname" . }}
  namespace: {{ template "imgproxy.namespace" . }}
  labels:
    {{- include "imgproxy.labels" . | nindent 4 }}
{{- if .Values.podDisruptionBudget.labels }}
{{ toYaml .Values.podDisruptionBudget.labels | indent 4 }}
{{- end }}
  {{- if .Values.podDisruptionBudget.annotations }}
  annotations:
  {{- range $key, $value := .Values.podDisruptionBudget.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "imgproxy.selectorLabels" . | nindent 6 }}
{{- end }}